# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csvt < Formula
  desc "Command line tool for processing CSV"
  homepage "https://github.com/onozaty/csvt"
  version "1.15.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onozaty/csvt/releases/download/v1.15.1/csvt_v1.15.1_Darwin_x86_64.tar.gz"
      sha256 "fffdf8e8d7b3729f0a8b1d6a44a1027be436869087260077f726414fea86cc01"

      def install
        bin.install "csvt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onozaty/csvt/releases/download/v1.15.1/csvt_v1.15.1_Darwin_arm64.tar.gz"
      sha256 "cab12150c4697a10e846931b6c959c0ad2e8ed9f4ef1c9b69dc89cd42e5d3ea7"

      def install
        bin.install "csvt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onozaty/csvt/releases/download/v1.15.1/csvt_v1.15.1_Linux_x86_64.tar.gz"
      sha256 "b871778c937ccf502d8c104e94955f8c61833b4c9fd765cfdf86b7cbb0125598"
      def install
        bin.install "csvt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onozaty/csvt/releases/download/v1.15.1/csvt_v1.15.1_Linux_arm64.tar.gz"
      sha256 "c6b06ebeae92ab4c1e41deff269738a8cd1ab6c138890585b3b9ca68d61a5a05"
      def install
        bin.install "csvt"
      end
    end
  end
end
