# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xml2csv < Formula
  desc "xml2csv converts XML to CSV. You can easily define mappings for converts using XPath."
  homepage "https://github.com/onozaty/xml2csv"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onozaty/xml2csv/releases/download/v1.2.2/xml2csv_v1.2.2_Darwin_x86_64.tar.gz"
      sha256 "a683af9359ed72471a73033220ddd6b6c6c1764e64e15cafb97a376b4f4ec0c8"

      def install
        bin.install "xml2csv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onozaty/xml2csv/releases/download/v1.2.2/xml2csv_v1.2.2_Darwin_arm64.tar.gz"
      sha256 "c9f1528883c7106889571c8c13d142a4466d155c3fdcd3f6b7ae4cb26ed07f29"

      def install
        bin.install "xml2csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onozaty/xml2csv/releases/download/v1.2.2/xml2csv_v1.2.2_Linux_x86_64.tar.gz"
      sha256 "a4690230b3815441f0b01561d76b34bd53bc1b59c502a7a16752759c6ceb225b"
      def install
        bin.install "xml2csv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onozaty/xml2csv/releases/download/v1.2.2/xml2csv_v1.2.2_Linux_arm64.tar.gz"
      sha256 "1c845e69a8c35b3de5fbc5d372e2a51e2624137b474c4d00a0ee83fd54d1fa81"
      def install
        bin.install "xml2csv"
      end
    end
  end
end
