# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xml2csv < Formula
  desc "xml2csv converts XML to CSV. You can easily define mappings for converts using XPath."
  homepage "https://github.com/onozaty/xml2csv"
  version "1.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onozaty/xml2csv/releases/download/v1.2.3/xml2csv_v1.2.3_Darwin_x86_64.tar.gz"
      sha256 "e6059c348e2344944fc56717eae0a19929ab560921b94aeeb978981c2a3d049d"

      def install
        bin.install "xml2csv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onozaty/xml2csv/releases/download/v1.2.3/xml2csv_v1.2.3_Darwin_arm64.tar.gz"
      sha256 "c63069a07d52d38713e5d537f670b6b6ac6c11ff8b35483630b5f89357e0bfe3"

      def install
        bin.install "xml2csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onozaty/xml2csv/releases/download/v1.2.3/xml2csv_v1.2.3_Linux_x86_64.tar.gz"
      sha256 "6d62f60112c4506ad3e4274a6209062f40bd569c7cb7cc218069d115b1087b35"
      def install
        bin.install "xml2csv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onozaty/xml2csv/releases/download/v1.2.3/xml2csv_v1.2.3_Linux_arm64.tar.gz"
      sha256 "49c68feb3a59510d8994a8df387d60f1fd6259b695822b63e29b233774f7eafa"
      def install
        bin.install "xml2csv"
      end
    end
  end
end
