# This file was generated by GoReleaser. DO NOT EDIT.
cask "csvt" do
  name "csvt"
  desc "Command line tool for processing CSV"
  homepage "https://github.com/onozaty/csvt"
  version "1.15.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "csvt"

  on_macos do
    on_intel do
      url "https://github.com/onozaty/csvt/releases/download/v#{version}/csvt_v#{version}_Darwin_x86_64.tar.gz"
      sha256 "756f361581f5cce0a4fb22fd53022536b827f2bd443734a5eaf5e5583d5e9bc8"
    end
    on_arm do
      url "https://github.com/onozaty/csvt/releases/download/v#{version}/csvt_v#{version}_Darwin_arm64.tar.gz"
      sha256 "0026b13061b51ae7b7eb58a678a044a4d579dba045a3a1a13e4d35bd0dc5a18e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onozaty/csvt/releases/download/v#{version}/csvt_v#{version}_Linux_x86_64.tar.gz"
      sha256 "acff77495336b58b4a77817449c9fb1848b224e34ff37d2f554c5b68d60a85a1"
    end
    on_arm do
      url "https://github.com/onozaty/csvt/releases/download/v#{version}/csvt_v#{version}_Linux_arm64.tar.gz"
      sha256 "1be36e4e1b56c274de199e6c6cbc025d5be804bcd456fde834f3ac4f7aee3dc6"
    end
  end

  # No zap stanza required
end
