# This file was generated by GoReleaser. DO NOT EDIT.
cask "filep" do
  name "filep"
  desc "A powerful command-line file processing tool"
  homepage "https://github.com/onozaty/filep"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filep"

  on_macos do
    on_intel do
      url "https://github.com/onozaty/filep/releases/download/v#{version}/filep_v#{version}_Darwin_x86_64.tar.gz"
      sha256 "b25cf68d75975cb9822ad8a48daceeab7303619b445442159de3ce65031b1212"
    end
    on_arm do
      url "https://github.com/onozaty/filep/releases/download/v#{version}/filep_v#{version}_Darwin_arm64.tar.gz"
      sha256 "5b0740d9bff26db7cdfd735a6f9cbfce5cc466a3ca0c9b46d17d868352cd7c0a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onozaty/filep/releases/download/v#{version}/filep_v#{version}_Linux_x86_64.tar.gz"
      sha256 "a102bec4cc3d04d125bab40c165c297ec2e37307ea8488e5195383a2ae020c9f"
    end
    on_arm do
      url "https://github.com/onozaty/filep/releases/download/v#{version}/filep_v#{version}_Linux_arm64.tar.gz"
      sha256 "23712efcfbfd4916cc6950053b68aa2abb5cd1b1c1cf9e36393822bad15d3d8c"
    end
  end

  # No zap stanza required
end
