# This file was generated by GoReleaser. DO NOT EDIT.
cask "filep" do
  name "filep"
  desc "A powerful command-line file processing tool"
  homepage "https://github.com/onozaty/filep"
  version "1.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filep"

  on_macos do
    on_intel do
      url "https://github.com/onozaty/filep/releases/download/v#{version}/filep_v#{version}_Darwin_x86_64.tar.gz"
      sha256 "e6657a318c05a5ba09479f294a01aa48a2a250531e8fea1f135cf02bec19ba40"
    end
    on_arm do
      url "https://github.com/onozaty/filep/releases/download/v#{version}/filep_v#{version}_Darwin_arm64.tar.gz"
      sha256 "fd3030d246ec418720436dec95f0f8b4f619b233ae4b867a1dab959daf06deb2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onozaty/filep/releases/download/v#{version}/filep_v#{version}_Linux_x86_64.tar.gz"
      sha256 "eb3795c2bc4e7443452346f6b85c079aed317e4d459412a461c86945ebfe56cb"
    end
    on_arm do
      url "https://github.com/onozaty/filep/releases/download/v#{version}/filep_v#{version}_Linux_arm64.tar.gz"
      sha256 "1c668579593f5f3e5dabf614d4c110ffed4501a9cfd132147d475940e596e7f6"
    end
  end

  # No zap stanza required
end
