# This file was generated by GoReleaser. DO NOT EDIT.
cask "filist" do
  name "filist"
  desc "A flexible command-line tool to list files with various information"
  homepage "https://github.com/onozaty/filist"
  version "1.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filist"

  on_macos do
    on_intel do
      url "https://github.com/onozaty/filist/releases/download/v#{version}/filist_v#{version}_Darwin_x86_64.tar.gz"
      sha256 "adfec3238dd9a283840857e81d6965a85c42604040851c5ccad64400c8612a83"
    end
    on_arm do
      url "https://github.com/onozaty/filist/releases/download/v#{version}/filist_v#{version}_Darwin_arm64.tar.gz"
      sha256 "cb29c8d0764307d7420e1fd8599b2aef56007a528e9824745f19d98379899a5e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onozaty/filist/releases/download/v#{version}/filist_v#{version}_Linux_x86_64.tar.gz"
      sha256 "ff4ec2f08a7999958ede184209d73f6a91d74c3246d0e65ebac4cac3902b39ce"
    end
    on_arm do
      url "https://github.com/onozaty/filist/releases/download/v#{version}/filist_v#{version}_Linux_arm64.tar.gz"
      sha256 "b42589d4447049de0e6231d6c293877c37df4e2b96a87b01965352dd80336b86"
    end
  end

  # No zap stanza required
end
