# This file was generated by GoReleaser. DO NOT EDIT.
cask "reporg" do
  name "reporg"
  desc "CLI tool that searches Git repositories using ripgrep and outputs results in TSV format"
  homepage "https://github.com/onozaty/reporg"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reporg"
  depends_on formula: [
      "ripgrep",
    ]

  on_macos do
    on_intel do
      url "https://github.com/onozaty/reporg/releases/download/v#{version}/reporg_v#{version}_Darwin_x86_64.tar.gz"
      sha256 "7391d56e48069be89d91f084ca387d9c37aef4c76173b2eda92af98eea595e87"
    end
    on_arm do
      url "https://github.com/onozaty/reporg/releases/download/v#{version}/reporg_v#{version}_Darwin_arm64.tar.gz"
      sha256 "dbfa7f4dbd5d8256875e7f891d9ee42b7ea5f71a6b9ba82906151e5e2f3f9007"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onozaty/reporg/releases/download/v#{version}/reporg_v#{version}_Linux_x86_64.tar.gz"
      sha256 "48b370f816a79ca706134f5753f792cca36f17192ebce8db33a8cd0481ab72bf"
    end
    on_arm do
      url "https://github.com/onozaty/reporg/releases/download/v#{version}/reporg_v#{version}_Linux_arm64.tar.gz"
      sha256 "0c77897fced941aed00add03000f2d807559817fffb86f948ade39cb010389f5"
    end
  end

  # No zap stanza required
end
