# This file was generated by GoReleaser. DO NOT EDIT.
cask "treecat" do
  name "treecat"
  desc "Combine multiple files into a single output with directory tree visualization, optimized for LLM consumption"
  homepage "https://github.com/onozaty/treecat"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "treecat"

  on_macos do
    on_intel do
      url "https://github.com/onozaty/treecat/releases/download/v#{version}/treecat_v#{version}_Darwin_x86_64.tar.gz"
      sha256 "e8fb52a110210fe8a7cd9b743f4f7f85a96fa6f7bfb76a944efe944795757aa3"
    end
    on_arm do
      url "https://github.com/onozaty/treecat/releases/download/v#{version}/treecat_v#{version}_Darwin_arm64.tar.gz"
      sha256 "6bbd2d79c38ae1ad6d8e868cc0fcf3fc05ef1cea527fc0e6b635d9802581730a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onozaty/treecat/releases/download/v#{version}/treecat_v#{version}_Linux_x86_64.tar.gz"
      sha256 "2f7d0cecb30071f0f47fcdb63fade597f2c0b17f448b0745ecc5f27ee7a0d231"
    end
    on_arm do
      url "https://github.com/onozaty/treecat/releases/download/v#{version}/treecat_v#{version}_Linux_arm64.tar.gz"
      sha256 "e2b935b457160a7aa039f526bf4afb9926865bfd1bd669531f8f4a1627c49fcf"
    end
  end

  # No zap stanza required
end
