# This file was generated by GoReleaser. DO NOT EDIT.
cask "xml2csv" do
  name "xml2csv"
  desc "xml2csv converts XML to CSV. You can easily define mappings for converts using XPath."
  homepage "https://github.com/onozaty/xml2csv"
  version "1.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xml2csv"

  on_macos do
    on_intel do
      url "https://github.com/onozaty/xml2csv/releases/download/v#{version}/xml2csv_v#{version}_Darwin_x86_64.tar.gz"
      sha256 "1f6a1778babe50b08e2c376d7f8bcc5cd20716ec5f3ff5dc1b8a7aafa40448c9"
    end
    on_arm do
      url "https://github.com/onozaty/xml2csv/releases/download/v#{version}/xml2csv_v#{version}_Darwin_arm64.tar.gz"
      sha256 "716098e541e70690d6e5c00bc5b3216e5d71dfee1015997599c06353fdf9d6e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onozaty/xml2csv/releases/download/v#{version}/xml2csv_v#{version}_Linux_x86_64.tar.gz"
      sha256 "4da098464bfd482bd879c1c34de6332c1012602fce4b644aaf65a3249c21d808"
    end
    on_arm do
      url "https://github.com/onozaty/xml2csv/releases/download/v#{version}/xml2csv_v#{version}_Linux_arm64.tar.gz"
      sha256 "4d722ac380120e44051cae837ff0543071b4cd71d2bf83ca825b93ba2704152d"
    end
  end

  # No zap stanza required
end
